### ISSUE TITLE
Searchgui setup failing with singularity

### ISSUE THREAD

**Issue by flevander** [wombat-p/WOMBAT-Pipelines#11]
### Description of the bug

When using the singularity profile, the workflow fails at the PREPARE_SEARCHGUI step. The error appears when trying to save the parameters file, despite the '--writable-tmpfs' singularity run option being enabled in nextflow.config. 

### Command used and terminal output

```console
$ nextflow run main.nf --parameters test_params.yml --raws 'raws/*' --fasta uniprot_contaminant_yeast_ups_prot_03022023.fasta --sdrf sdrf_proline_ed.tsv -profile singularity
```

### System information

nextflow 23.04.2 build 5870
singularity-ce version 3.11.4-focal
Ubuntu 22.04
wombat-pipelines 0.9.1

**Comment by flevander** [comment]
The specific error output is in COMPOMICS:PREPARE_SEARCHGUI

Command executed:

  mkdir tmp
  mkdir log
  searchgui eu.isas.searchgui.cmd.PathSettingsCLI -temp_folder ./tmp -log ./log
  searchgui eu.isas.searchgui.cmd.IdentificationParametersCLI -out searchgui \ .....

Command output:
  An error occurred when saving the path preference to /usr/local/share/searchgui-4.2.9-0/resources/conf/paths.txt.

**Comment by veitveit** [comment]
I checked the docker container. There the respective folder is only writable by root. This could be issue. 

As far as I oversee it now, the problem is that any change of user rights seem to be overwritten when installing the package via conda and then automatically making a docker container. We might need a specific container for searchgui and peptideshaker, where these rights are provided.

**Comment by veitveit** [comment]
This solved the issues when running with singularity:
- Create new docker containers veitveit/searchgui... and veitveit/peptideshaker... with these folders made writable.
- The process call of flashLFQ needed specific setting of some environmental variables as they were overwritten by nextflow. 

This fixes work but are a bit dirty so far.

@flevander
